### PR TITLE
chore(ci): remove publish to GitHub Registry

### PR DESCRIPTION
**Pull request by ShGKme**

### CODE REVIEW

**Review by Antreesy — COMMENTED** [review]
Three more libraries to go

**Review by Antreesy — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by skjnldsv** [comment]
What's the reason behind this? :)

**Comment by ShGKme** [comment]
@skjnldsv Is the question still actual? :D

**Comment by skjnldsv** [comment]
Yeah. Feels like providing more than npm as an alternative is what foss is all about :grin:

**Pull request merged**
